# Generated by Django 3.0.6 on 2020-05-31 13:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'Account',
                'verbose_name_plural': 'Accounts',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='money pair')),
                ('volume', models.DecimalField(decimal_places=2, max_digits=20, verbose_name='Volume')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Create date')),
                ('side', models.CharField(choices=[('buy', 'Buy order'), ('sell', 'Sell order')], default='sell', max_length=15)),
                ('price', models.DecimalField(decimal_places=2, max_digits=20)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.Account')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
            },
        ),
    ]
