# Generated by Django 3.0.6 on 2020-06-03 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='account', to='orders.Account'),
        ),
        migrations.AlterField(
            model_name='order',
            name='symbol',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='symbol'),
        ),
        migrations.AlterField(
            model_name='order',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=20, verbose_name='volume'),
        ),
    ]
