# Generated by Django 3.0.6 on 2020-06-03 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20200603_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(blank=True, default=None, max_length=50, null=True, verbose_name='order_type'),
        ),
    ]
