# Generated by Django 3.0.6 on 2020-06-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='account',
            name='api_secret',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='Name'),
        ),
    ]
