# Generated by Django 3.0.6 on 2020-06-04 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200604_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='api_key',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='API_KEY'),
        ),
        migrations.AlterField(
            model_name='account',
            name='api_secret',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, unique=True, verbose_name='API_SECRET'),
        ),
    ]
